### ISSUE TITLE
There is a difference in condition to infer whether requested srcset is dpr based .

### ISSUE THREAD

**Issue by i10416** [imgix/imgix-go#28]
**Before you submit:**

- [x] Please search through the [existing issues](https://github.com/imgix/imgix-go/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your question has already been discussed.

**Question**
[isDprBased](https://github.com/imgix/imgix-go/blob/506aa34d13b4daf3306318128028a1850b3833de/v2/srcset.go#L227) returns true only if parameters contain 'w' or ('h' and 'ar') while [here](https://github.com/imgix/imgix-go/blob/506aa34d13b4daf3306318128028a1850b3833de/v2/srcset.go#L90) and [test](https://github.com/imgix/imgix-go/blob/506aa34d13b4daf3306318128028a1850b3833de/v2/srcset_test.go#L103) assume requested srcset is dpr based when params just contain 'h' even if params do not contain 'ar'.

Which rule is right?
Besides, It seems that `isDprBased` is not used. Maybe is this function  deprecated?

**Comment by sherwinski** [comment]
Hey @ItoYo16u, great catch and you are correct: a srcset should only be DPR-based if the parameters contain `w` or `h`. In this case, the tests are correct and `isDprBased` should be fixed. I've made an item in our backlog to correct this sometime in the future.
